### ISSUE TITLE
Lacking .npy files

### ISSUE THREAD

**Issue by YaokangHuang** [terarachang/ACCV_TinyGAN#2]
Where can I get the `'out_img'` `'all_noises.npy'` `'all_labels.npy'` used in `train.sh`?
Which part of ImageNet datasets should I download? How to arrange the corresponding directories?

**Comment by terarachang** [comment]
Hi,

Before training the model, you first need to:
1. collect data from BigGAN:
Please run
https://github.com/terarachang/ACCV_TinyGAN/blob/master/misc/extract_big.py
and arrange the collected data like this:
YOUR_DIR
  |- out_img
  |- all_noises.npy
  |- all_labels.npy

2. download the ImageNet training set, unzip it, and preprocess the images
(I did not re-arrange the directories)
To crop & resize the image,
I used the source code from: https://github.com/pfnet-research/sngan_projection

I hope I've answered all your questions.
Please let me know if you have further questions.

Thanks,
Ting-Yun
