### ISSUE TITLE
 Hello, this error is reported step by step and cannot be solved 

### ISSUE THREAD

**Issue by KivenGood** [terarachang/ACCV_TinyGAN#3]
Hello, this error is reported step by step and cannot be solved.
In file "/pcb/TinyGAN/solver.py", line 135,
![2020-12-30 12-33-29屏幕截图](https://user-images.githubusercontent.com/28687350/103332103-c5960500-4aa3-11eb-9eca-119676eff26a.png)
![2020-12-30 12-32-35屏幕截图](https://user-images.githubusercontent.com/28687350/103332106-c6c73200-4aa3-11eb-8e04-acb2e7622e47.png)

**Comment by terarachang** [comment]
Hi,

Let me explain this part of the code.
First, the model will *try* to ask for a batch of data from ImageNet;
if failed, which always happens at the very first time you launch this program
as well as every time it uses up/trains on all the data in ImageNet,
it would go into *except* to reload the *real_iter*.

I'm not sure why your code failed, but it is highly possible that there is something wrong with your *real_loader*.
Please check line 25 & 134 to see if *real_loader* is correctly linked to the ImageNet data.
If not, please check line 30 in main.py, specifically, to check what your *config.real_dir* is pointing to.
You can see my reply to #issue2 for more details about how to organize the ImageNet data.
Or, you can simply disable all the lines concerning *x_real2, label2*, which will lead to some drop in performance, 
but the program is still runnable (please see more in the ablation study in the paper). 

Thank you,
Ting-Yun Chang
