### ISSUE TITLE
Results on whole ImageNet dataset

### ISSUE THREAD

**Issue by vominhduc** [terarachang/ACCV_TinyGAN#4]
Hi Chang,

Thank you for your interesting work. I have tried your method on the whole ImageNet dataset (1000 classes) but the results are weird. I am wondering if you are successful in dealing with 1000 classes?

Best,
Duc.

**Comment by terarachang** [comment]
Hi,

Unfortunately, our results on all 1000 classes are also miserable.
Please see our paper (**page 21**) for more discussion if you are interested:
https://arxiv.org/pdf/2009.13829.pdf

Thanks,
Ting-Yun
